### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by bangarharshit** [longkerdandy/mithqtt#39]
Thanks for the scalable mqtt java broker. Is there any wiki for installation instruction? What kind of deployment do you guys recommend for production? I can think of http and broker module to be independent and separately deployed. Apart from that I can think of a db servers (redis, influx)

Also wanted to check if you guys have done some load testing? I am planning to test it on 1.7gb aws machine (although I will be keeping it inside docker container and will be building images).

Thanks,
Harshit

**Comment by longkerdandy** [comment]
The open source project is not production ready yet.
We have a internal version based on v1.0.0Beta1 running in production environment, if you want to do some test, start from there.

I'm trying to improve the architecure a liitle bit by replace the overhead commmunicator choice. I'm planling to finished the document after next release.

The InflusDB based metrics is a liitle buggy, do not use it at the moment.

**Comment by bangarharshit** [comment]
Thanks. Makes sense. We really liked the concept of designing based on micro-services.  We are currently building an internal version of our server and so I think we can fix the bugs. 

It will still be awesome if you can write a basic wiki on installing from source and binary so that anyone can start and contribute.

**Comment by longkerdandy** [comment]
I've wrote a get started guide:
[Getting Started with Mithqtt Broker](https://mithqtt.readme.io/docs/getting-started)
More documents will be added in the future.
