### ISSUE TITLE
why document like this

### ISSUE THREAD

**Issue by hanyou** [longkerdandy/mithqtt#43]
i can't read document on https://mithqtt.readme.io/docs, every chapter dispaly like below:

Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec massa tristique arcu ferme.

1. First Step
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec massa tristique arcu fermentum dapibus. Integer orci turpis, mollis vel augue eget, placerat rhoncus orci. Mauris metus libero, rutrum eu ornare ut, molestie vel nunc. Morbi sed iaculis metus.

**Comment by longkerdandy** [comment]
Sorry, the document is not finished yet.

**Comment by hanyou** [comment]
About completion time?

**Comment by hanyou** [comment]
I want use mithqtt to build our server, but have not document, I don't know how to do.

**Comment by longkerdandy** [comment]
I've wrote a get started guide:
[Getting Started with Mithqtt Broker](https://mithqtt.readme.io/docs/getting-started)
More documents will be added in the future.

**Comment by longkerdandy** [comment]
Since this issue is duplicated with #39 , I'm closing this one.
