### ISSUE TITLE
Which projects are using this mithqtt?

### ISSUE THREAD

**Issue by hanyou** [longkerdandy/mithqtt#44]
Which projects are using this mithqtt?

有没有大的公司正在使用这个mithqtt这个后台？

**Comment by longkerdandy** [comment]
My former employer use Mithqtt in production evnironment, which is a New Energy IoT Cloud project.
They're using the v1.0 branch for quite a while, so for it is stable.
But this project itself is still in the early stage, if you consider using it, I suggest two options:
1. Using Mithqtt to see if it is stable enough, it can be easily replaced by another MQTT broker.
2. Using another MQTT broker, and change to Mithqtt when your platform needs to scale.
